services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: esxi-lab-scheduler:latest
    container_name: esxi-lab-scheduler
    network_mode: host
    env_file:
      - .env
    volumes:
      - ${HOST_PROJECT_PATH:-/home/vlad/Documents/esxi-lab-provider}/infra/terraform/service-account.json:/app/config/service-account.json:ro
    restart: "no"

  cron:
    image: alpine:latest
    container_name: esxi-lab-cron
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: >
      sh -c "
      apk add --no-cache docker-cli tzdata &&
      echo '0 * * * * docker start -a esxi-lab-scheduler >> /var/log/cron.log 2>&1' | crontab - &&
      crond -f -l 2
      "

networks:
  default:
    name: esxi-lab-network
