name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.x'

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '1.26'
          cache-dependency-path: api/go.sum

      - name: Install golangci-lint
        env:
          # renovate: datasource=github-releases depName=golangci/golangci-lint
          GOLANGCI_LINT_VERSION: v2.5.0
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin "$GOLANGCI_LINT_VERSION"
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@9d84900f3238fab8cd84ce47d658d25dd008be2f # v1
        with:
          # renovate: datasource=github-releases depName=opentofu/opentofu
          tofu_version: 1.6.0

      - name: Install tflint
        env:
          # renovate: datasource=github-releases depName=terraform-linters/tflint
          TFLINT_VERSION: v0.57.0
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  go-test:
    name: Go tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: '1.26'
          cache-dependency-path: api/go.sum

      - name: Download dependencies
        working-directory: ./api
        run: go mod download

      - name: Run tests
        working-directory: ./api
        run: go test -v ./...

      - name: Build
        working-directory: ./api
        run: go build -v ./cmd/server/main.go
